### ISSUE TITLE
avc granted messages on dhcp updates for unbound caused by coreutils-sort

### ISSUE THREAD

**Issue by tobiaswaldvogel** [DefenSec/selinux-policy#26]
I'm using unbound as DNS resolver and the script `/usr/lib/unbound/odhcpd.sh` for updating the local entries upon a DHCP lease change. This seems to trigger the following messages. This is certainly not an important issue, but it would be nice to silence these messages.  For the busybox built in sort probably there wouldn't be any message at all, but addblock pulls in coreutils-sort. So probably that would require then targeting coreutils, or at least sort in this case.

```
avc:  granted  { execute_no_trans } for  pid=11020 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=11023 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=11049 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=11051 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=11053 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=12280 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=12283 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=12309 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=12311 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=12313 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=12421 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=12423 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=12425 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file
avc:  granted  { execute_no_trans } for  pid=12447 comm="sh" path="/usr/libexec/sort-coreutils" dev="overlay" ino=2749 scontext=u:r:unbound.odhcpd.subj tcontext=u:r:file.execfile tclass=file

```

**Comment by doverride** [comment]
Eventually that auditallow rule should indeed be removed, but why are you bothered by these "granted" messages?

**Comment by tobiaswaldvogel** [comment]
Actually I like rule and the idea, of having a log of any execution of anything with just file.execfile.

In this particular case it is just the pure amount of messages, which make the kernel log unreadable. I have quite lot of devices so DHCP renewals in total are quite frequent. Well, for now I can also just increase the lease time from 12h to 5days. Most leases are static anyway.

**Comment by doverride** [comment]
I think the kernel ring buffer rotates automatically every 256KB but yes it might be bit annoying if you have standalone coreutils. I got used to the kernel ring buffer noise. I have this wireguard cron script that runs every minute polluting the logs:

```
Mon Nov  1 19:30:00 2021 cron.err crond[1220]: USER root pid 2632 cmd /usr/bin/wireguard_watchdog
```

**Comment by doverride** [comment]
Err, make that logread... but yes one of these day's I will remove it.

**Comment by doverride** [comment]
I removed it. You are right this should not be here. But i encourage you to add the rule to your local development policy so that you know what commands your domains execute to determine whether it needs to be targeted.

**Comment by tobiaswaldvogel** [comment]
Like you said, I think it makes sense to have the auditallow rule to identify what is going on.
For the coreutils probably it makes sense to run them without a context transition, as they are more general purpose commands used by shell scripts. So I came up with something like this

```
(in .file
    (call .coreutils.obj_type_transition_execfile (unconfined.subj_typeattr)))

(block coreutils

       (filecon
        "/usr/libexec/.*-coreutils"
        file
        execfile_file_context)

       (macro obj_type_transition_execfile ((type ARG1))
              (call .file.execfile_obj_type_transition
                    (ARG1 execfile file "sort-coreutils")))

       (blockinherit .file.exec.obj_template))
```

And then adding it to shell.execute_execfile_files 

```
              (optional shell_opt_coreutils
                    (call .coreutils.execute_execfile_files (subj))))
```

Unfortunately the libexec directory is not exclusively used for the coreutils package, so this would require then an individual call for each utility I'm afraid. As far as I remember the type_transition does just a simple string compare and does not allow wildcards or regex.

**Comment by doverride** [comment]
I considered that but its not always that simple when you can just match *-coreutils, would possibly be hard to maintain over time. Regardless that is actually the purpose if .exec.file (public executable files)

But yes,, we as developers should add that auditallow rule to our local development policy but that "stable" policy that goes to the user shouldnt have that rule ideally.

**Comment by doverride** [comment]
I also did this for the various *-tiny variants and other special cases

**Comment by doverride** [comment]
Also /usr/libexec is treated identical to /usr/bin with equivalence rules:

https://github.com/DefenSec/selinux-policy/blob/master/file_contexts.subs_dist#L19

So all fc specs and file transitions that apply to /usr/bin also automatically apply to /usr/libexec
